// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5naX5TKE4J4CUjZzLO_I5OajnnVZd_74',
    appId: '1:191802887937:web:10b1e5e0df85eb034bd500',
    messagingSenderId: '191802887937',
    projectId: 'bookswapapp-1cabc',
    authDomain: 'bookswapapp-1cabc.firebaseapp.com',
    storageBucket: 'bookswapapp-1cabc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGF68Y9W1EuSaG4gwOngeUibtXhBcCoI',
    appId: '1:191802887937:android:ad338dacf60aec524bd500',
    messagingSenderId: '191802887937',
    projectId: 'bookswapapp-1cabc',
    storageBucket: 'bookswapapp-1cabc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ShMh8PT82YZlkRhTieOB9XlteXWjM7Q',
    appId: '1:191802887937:ios:431b2fc0b4120cba4bd500',
    messagingSenderId: '191802887937',
    projectId: 'bookswapapp-1cabc',
    storageBucket: 'bookswapapp-1cabc.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ShMh8PT82YZlkRhTieOB9XlteXWjM7Q',
    appId: '1:191802887937:ios:431b2fc0b4120cba4bd500',
    messagingSenderId: '191802887937',
    projectId: 'bookswapapp-1cabc',
    storageBucket: 'bookswapapp-1cabc.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5naX5TKE4J4CUjZzLO_I5OajnnVZd_74',
    appId: '1:191802887937:web:c12d7edd31b617f74bd500',
    messagingSenderId: '191802887937',
    projectId: 'bookswapapp-1cabc',
    authDomain: 'bookswapapp-1cabc.firebaseapp.com',
    storageBucket: 'bookswapapp-1cabc.firebasestorage.app',
  );

}